package com.kanban.domain.notification;

public enum NotificationType {
    COMMENT_MENTION,
    CHECKLIST_ASSIGNED,
    TASK_COMMENT,
    MEETING_MEMO_SHARED,
    NOTE_COMMENT_MENTION,
    ANNIVERSARY,
    PAYMENT_FAILED,
    BOARD_JOIN_REQUEST,
    BOARD_JOIN_APPROVED,
    BOARD_JOIN_REJECTED
}
