-- activity_log CHECK 제약 확장: PLANNING_CARD_* 액션 + PLANNING_CARD target_type 추가
-- SA-003에서 ActivityAction.PLANNING_CARD_CREATED/UPDATED/MOVED/DELETED 및
-- TargetType.PLANNING_CARD 가 추가되었으나 DB 레벨 CHECK 제약이 갱신되지 않아
-- INSERT 시 constraint 위반 가능성 존재 → 이 마이그레이션에서 해결.

-- 1. action CHECK 제약: PLANNING_CARD_* 4개 추가
ALTER TABLE activity_log DROP CONSTRAINT IF EXISTS activity_log_action_check;
ALTER TABLE activity_log ADD CONSTRAINT activity_log_action_check
    CHECK (action IN (
        'BOARD_CREATED', 'BOARD_UPDATED',
        'BLOCK_CREATED', 'BLOCK_UPDATED', 'BLOCK_DELETED', 'BLOCK_REORDERED',
        'FEATURE_CREATED', 'FEATURE_UPDATED', 'FEATURE_DELETED', 'FEATURE_COMPLETED',
        'TASK_CREATED', 'TASK_UPDATED', 'TASK_DELETED', 'TASK_MOVED', 'TASK_COMPLETED', 'TASK_REOPENED', 'TASK_FEATURE_MOVED',
        'CHECKLIST_CREATED', 'CHECKLIST_CHECKED', 'CHECKLIST_MOVED',
        'MEMBER_INVITED', 'MEMBER_JOINED', 'MEMBER_ROLE_CHANGED', 'MEMBER_REMOVED', 'MEMBER_LEFT',
        'TAG_CREATED', 'TAG_DELETED',
        'SUBSCRIPTION_STARTED', 'SUBSCRIPTION_CANCELED', 'SUBSCRIPTION_PLAN_CHANGED',
        'PLANNING_CARD_CREATED', 'PLANNING_CARD_UPDATED', 'PLANNING_CARD_MOVED', 'PLANNING_CARD_DELETED'
    ));

-- 2. target_type CHECK 제약: PLANNING_CARD 추가
ALTER TABLE activity_log DROP CONSTRAINT IF EXISTS activity_log_target_type_check;
ALTER TABLE activity_log ADD CONSTRAINT activity_log_target_type_check
    CHECK (target_type IN (
        'BOARD', 'BLOCK', 'FEATURE', 'TASK', 'CHECKLIST', 'MEMBER', 'TAG', 'SUBSCRIPTION',
        'PLANNING_CARD'
    ));
