-- 노트(자료실) 활동 로그 도입(aba54518, 2026-09-13)으로 추가된 ActivityAction / TargetType 값들을
-- activity_log CHECK 제약조건 화이트리스트에 반영.
--
-- 이전 마이그레이션(V20260716_110606) 이후 ActivityAction enum에 NOTE_* 9개, TargetType enum에 NOTE 가
-- 추가되었으나 DB CHECK 제약이 갱신되지 않아, 노트 생성/저장(발행)/삭제/복구/공유/상태 변경 시
-- activity_log INSERT 가 constraint violation → 트랜잭션 롤백 → 500(DataIntegrityViolationException) 발생.
-- (NoteService.logNoteActivity 의 try/catch 는 INSERT 가 커밋 시점 flush 에서 실행되므로 잡지 못한다.)
--   NOTE_CREATED, NOTE_PUBLISHED, NOTE_DELETED, NOTE_RESTORED, NOTE_PERMANENTLY_DELETED,
--   NOTE_VERSION_RESTORED, NOTE_SHARED, NOTE_UNSHARED, NOTE_STATUS_CHANGED
--
-- 과거 PLANNING_CARD_* 레코드 보존을 위해 레거시 값은 화이트리스트에 유지한다.

ALTER TABLE activity_log DROP CONSTRAINT IF EXISTS activity_log_action_check;
ALTER TABLE activity_log ADD CONSTRAINT activity_log_action_check
    CHECK (action IN (
        'BOARD_CREATED', 'BOARD_UPDATED',
        'BLOCK_CREATED', 'BLOCK_UPDATED', 'BLOCK_DELETED', 'BLOCK_REORDERED',
        'FEATURE_CREATED', 'FEATURE_UPDATED', 'FEATURE_DELETED', 'FEATURE_COMPLETED',
        'FEATURE_RESTORED', 'FEATURE_PERMANENTLY_DELETED',
        'TASK_CREATED', 'TASK_UPDATED', 'TASK_DELETED', 'TASK_MOVED', 'TASK_COMPLETED', 'TASK_REOPENED', 'TASK_FEATURE_MOVED',
        'TASK_RESTORED', 'TASK_PERMANENTLY_DELETED',
        'CHECKLIST_CREATED', 'CHECKLIST_CHECKED', 'CHECKLIST_MOVED',
        'CHECKLIST_RENAMED', 'CHECKLIST_REASSIGNED', 'CHECKLIST_RESCHEDULED', 'CHECKLIST_MERGED',
        'CHECKLIST_DELETED', 'CHECKLIST_RESTORED', 'CHECKLIST_PERMANENTLY_DELETED',
        'MEMBER_INVITED', 'MEMBER_JOINED', 'MEMBER_ROLE_CHANGED', 'MEMBER_REMOVED', 'MEMBER_LEFT',
        'TAG_CREATED', 'TAG_DELETED',
        'SUBSCRIPTION_STARTED', 'SUBSCRIPTION_CANCELED', 'SUBSCRIPTION_PLAN_CHANGED',
        'NOTE_CREATED', 'NOTE_PUBLISHED', 'NOTE_DELETED', 'NOTE_RESTORED', 'NOTE_PERMANENTLY_DELETED',
        'NOTE_VERSION_RESTORED', 'NOTE_SHARED', 'NOTE_UNSHARED', 'NOTE_STATUS_CHANGED',
        'PLANNING_CARD_CREATED', 'PLANNING_CARD_UPDATED', 'PLANNING_CARD_MOVED', 'PLANNING_CARD_DELETED'
    ));

ALTER TABLE activity_log DROP CONSTRAINT IF EXISTS activity_log_target_type_check;
ALTER TABLE activity_log ADD CONSTRAINT activity_log_target_type_check
    CHECK (target_type IN (
        'BOARD', 'BLOCK', 'FEATURE', 'TASK', 'CHECKLIST', 'MEMBER', 'TAG', 'SUBSCRIPTION', 'NOTE',
        'PLANNING_CARD'
    ));
