-- 트래시 기능(휴지통/복구/영구삭제) 도입으로 추가된 ActivityAction 값들을
-- activity_log.action CHECK 제약조건 화이트리스트에 반영.
--
-- 이전 마이그레이션(V20260421_080819)이후 ActivityAction enum에 다음 7개가 추가되었으나
-- DB CHECK 제약이 갱신되지 않아 INSERT 시 constraint violation으로 500 발생:
--   CHECKLIST_DELETED, CHECKLIST_RESTORED, CHECKLIST_PERMANENTLY_DELETED,
--   FEATURE_RESTORED, FEATURE_PERMANENTLY_DELETED,
--   TASK_RESTORED, TASK_PERMANENTLY_DELETED

ALTER TABLE activity_log DROP CONSTRAINT IF EXISTS activity_log_action_check;
ALTER TABLE activity_log ADD CONSTRAINT activity_log_action_check
    CHECK (action IN (
        'BOARD_CREATED', 'BOARD_UPDATED',
        'BLOCK_CREATED', 'BLOCK_UPDATED', 'BLOCK_DELETED', 'BLOCK_REORDERED',
        'FEATURE_CREATED', 'FEATURE_UPDATED', 'FEATURE_DELETED', 'FEATURE_COMPLETED',
        'FEATURE_RESTORED', 'FEATURE_PERMANENTLY_DELETED',
        'TASK_CREATED', 'TASK_UPDATED', 'TASK_DELETED', 'TASK_MOVED', 'TASK_COMPLETED', 'TASK_REOPENED', 'TASK_FEATURE_MOVED',
        'TASK_RESTORED', 'TASK_PERMANENTLY_DELETED',
        'CHECKLIST_CREATED', 'CHECKLIST_CHECKED', 'CHECKLIST_MOVED',
        'CHECKLIST_DELETED', 'CHECKLIST_RESTORED', 'CHECKLIST_PERMANENTLY_DELETED',
        'MEMBER_INVITED', 'MEMBER_JOINED', 'MEMBER_ROLE_CHANGED', 'MEMBER_REMOVED', 'MEMBER_LEFT',
        'TAG_CREATED', 'TAG_DELETED',
        'SUBSCRIPTION_STARTED', 'SUBSCRIPTION_CANCELED', 'SUBSCRIPTION_PLAN_CHANGED',
        'PLANNING_CARD_CREATED', 'PLANNING_CARD_UPDATED', 'PLANNING_CARD_MOVED', 'PLANNING_CARD_DELETED'
    ));
