-- activity_log 테이블의 action CHECK 제약조건에 CHECKLIST_MOVED 추가
ALTER TABLE activity_log DROP CONSTRAINT IF EXISTS activity_log_action_check;
ALTER TABLE activity_log ADD CONSTRAINT activity_log_action_check
    CHECK (action IN (
        'BOARD_CREATED', 'BOARD_UPDATED',
        'BLOCK_CREATED', 'BLOCK_UPDATED', 'BLOCK_DELETED', 'BLOCK_REORDERED',
        'FEATURE_CREATED', 'FEATURE_UPDATED', 'FEATURE_DELETED', 'FEATURE_COMPLETED',
        'TASK_CREATED', 'TASK_UPDATED', 'TASK_DELETED', 'TASK_MOVED', 'TASK_COMPLETED', 'TASK_REOPENED', 'TASK_FEATURE_MOVED',
        'CHECKLIST_CREATED', 'CHECKLIST_CHECKED', 'CHECKLIST_MOVED',
        'MEMBER_INVITED', 'MEMBER_JOINED', 'MEMBER_ROLE_CHANGED', 'MEMBER_REMOVED', 'MEMBER_LEFT',
        'TAG_CREATED', 'TAG_DELETED',
        'SUBSCRIPTION_STARTED', 'SUBSCRIPTION_CANCELED', 'SUBSCRIPTION_PLAN_CHANGED'
    ));
