package com.kanban.domain.organization;

public enum OrgActivityType {
    MEMBER_JOINED,
    MEMBER_LEFT,
    MEMBER_ROLE_CHANGED,
    BOARD_ADDED,
    BOARD_REMOVED,
    BOARD_CREATED,
    BOARD_DELETED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    ANNOUNCEMENT_POSTED,
    ANNIVERSARY_CELEBRATED,
    MANAGER_CHANGED,
    ONBOARDING_COMPLETED
}
